language: node_js
node_js:
  - "8.11.2"
cache:
  directories:
  - node_modules
script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $portfolio
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: develop